
services:
  db:
    image: postgres:17rc1 # Use 'latest' or a valid version like '15'
    volumes:
     # - ./tmp/db:/var/lib/postgresql/data
       - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: project_api_development

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b '0.0.0.0'"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://postgres:1234@db:5432/project_api_development
      REDIS_URL: redis://redis:6379/1
      #new
      DB_HOST: db
      DB_PORT: 5432
      #
      DB_USERNAME: postgres
      DB_PASSWORD: 1234
    depends_on:
      - db
      - redis

  sidekiq:
    build:
      context: .
      dockerfile: Dockerfile
    command: bundle exec sidekiq
    volumes:
      - .:/app
    depends_on:
      - db
      - redis

volumes:
  db_data:
