

default: &default

  #adapter: postgresql
  #encoding: unicode
  #pool: 5
  #host: db #<%= ENV['DB_HOST'] || 'localhost' %>
  #port: 5432
  #username: postgres
  #password: 1234
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: <%= ENV['DB_HOST'] || 'db' %>
  port: <%= ENV['DB_PORT'] || 5432 %>
  username: <%= ENV['DB_USERNAME'] || 'postgres' %>
  password: <%= ENV['DB_PASSWORD'] || '1234' %>
 
development:
  <<: *default
  database: project_api_development

  
test:
  <<: *default
  database: project_api_test


production:
  <<: *default
  database: project_api_production
  #username: project_api
  #password: <%= ENV["PROJECT_API_DATABASE_PASSWORD"] %>
  username: <%= ENV["PROJECT_API_DATABASE_USERNAME"] %>
  password: <%= ENV["PROJECT_API_DATABASE_PASSWORD"] %>

